// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukvvbhsezuvsjxgnylhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrdnZiaHNlenV2c2p4Z255bGhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY2MjU5NzEsImV4cCI6MjA5MjIwMTk3MX0.KIlSvLejgrgCSH1IZNsx3QntKBXLNQkG9_YlCSndGp8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});